#!/bin/bash

if [ $# -ne 3 ]; then
  echo "Usage: $0 <directory_to_compress> <destination_directory> <user:group>"
  exit 1
fi

DIRECTORY=$1
DESTINATION=$2
USER_GROUP=$3

if [ ! -d "$DIRECTORY" ]; then
  echo "Directory $DIRECTORY does not exist."
  exit 1
fi

if [ ! -d "$DESTINATION" ]; then
  echo "Destination directory $DESTINATION does not exist."
  exit 1
fi

if ! id -u "$(echo $USER_GROUP | cut -d':' -f1)" >/dev/null 2>&1; then
  echo "Specified user does not exist."
  exit 1
fi

if ! getent group "$(echo $USER_GROUP | cut -d':' -f2)" >/dev/null 2>&1; then
  echo "Specified group does not exist."
  exit 1
fi

FOLDER_NAME=$(basename "$DIRECTORY")
CURRENT_DATE=$(date +"%Y%m%d")
ZIP_FILE="${FOLDER_NAME}_${CURRENT_DATE}.zip"

zip -r "$ZIP_FILE" "$DIRECTORY"

if [ $? -eq 0 ]; then
  echo "Directory $DIRECTORY has been compressed into $ZIP_FILE"
else
  echo "Error compressing directory $DIRECTORY"
  exit 1
fi

for file in "$DESTINATION"/${FOLDER_NAME}_*.zip; do
  if [[ $file != *"$CURRENT_DATE"* ]]; then
    rm -f "$file"
  fi
done

cp "$ZIP_FILE" "$DESTINATION"

if [ $? -eq 0 ]; then
  echo "File $ZIP_FILE has been copied to $DESTINATION successfully."
else
  echo "Error copying file $ZIP_FILE to $DESTINATION"
  exit 1
fi

chown "$USER_GROUP" "$DESTINATION/$ZIP_FILE"

if [ $? -eq 0 ]; then
  echo "Owner of the file $DESTINATION/$ZIP_FILE has been changed to $USER_GROUP."
else
  echo "Error changing the owner of the file $DESTINATION/$ZIP_FILE"
  exit 1
fi

rm -f "$ZIP_FILE"

if [ $? -eq 0 ]; then
  echo "Original file $ZIP_FILE has been deleted."
else
  echo "Error deleting the original file $ZIP_FILE"
  exit 1
fi
